import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import '@stba/ui/styles.css'
import Navbar from "@stba/ui/Navbar";
import { Role } from "@stba/types/client";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Student panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar appName={Role.STUDENT} className="text-blue-600" />
        {children}
      </body>
    </html>
  );
}
