import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import '@stba/ui/styles.css'
import Navbar from "@stba/ui/Navbar";
import { Role } from "@stba/types/client"
import Toast from "@stba/ui/Toast";
import { UserProvider } from "@stba/ui/context/UserContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Admin panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <UserProvider>
          <Navbar appName={Role.ADMIN} className="text-red-600" />
          <main className="h-screen flex flex-col justify-between pt-20">
            {children}
          </main>
        </UserProvider>
        <Toast />
      </body>
    </html>
  );
}
